server:
  port: 9090
  servlet:
    context-path: /jpaTest
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    url: jdbc:mysql://localhost:3306/jpatest?useUnicode=true&characterEncoding=UTF-8&verifyServerCertificate=false&useSSL=false
    password: root
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
